### ISSUE TITLE
Time in iOS 14 Widget is not updated every minutes

### ISSUE THREAD

**Issue by renaudjenny** [renaudjenny/telltime#19]
Once you added the Widget, it will stick to the time it is when you selected it. It would be better that this time changes while the time pass by.

**Comment by talkaboutdesign** [comment]
This still seems to be the issue.

**Comment by renaudjenny** [comment]
@talkaboutdesign indeed, I just pushed a new commit: a1f7bdd8491f923467b4e62c00ccdec1563dcea8 and this should eventually fix the issue. Actually before I was updating the widget every minute, but not "floored" it could have been at 09:15:30 and then 09:31:30, 09:32:30 and so on. And now I take care to use `00` as seconds, so it should be fine.

Sorry for the late answer, I edited the code few days ago, but I was traveling and I didn't have internet connection 😄.
